owner: 5e-bits # GitHub username
repo: dnd-uptime # GitHub repository name
status-website:
  name: D&D API Status
  logoUrl: https://www.dnd5eapi.co/public/favicon.ico
  baseUrl: /dnd-uptime
  introTitle: "**Status** tracks the uptime of the D&D REST API"
  introMessage: This status page uses **real-time** data from our [Github repository](https://github.com/5e-bits/dnd-uptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /dnd-uptime
    - title: API
      href: https://github.com/5e-bits/5e-srd-api
    - title: Database
      href: https://github.com/5e-bits/5e-database

sites: # List of endpoints to track
  - name: DnD 5e API
    url: https://www.dnd5eapi.co/api

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
