owner: 5e-bits # GitHub username
repo: dnd-uptime # GitHub repository name
assignees:
  - bagelbits
status-website:
  name: D&D API Status
  theme: night
  logoUrl: https://www.dnd5eapi.co/public/favicon.ico
  baseUrl: /dnd-uptime
  introTitle: '**Status** tracks the uptime of the D&D REST API'
  introMessage: This status page uses **real-time** data from our [Github repository](https://github.com/5e-bits/dnd-uptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /dnd-uptime
    - title: API
      href: https://www.dnd5eapi.co
    - title: GraphQL
      href: https://www.dnd5eapi.co/graphql/2014
    - title: API Source
      href: https://github.com/5e-bits/5e-srd-api
    - title: Database Source
      href: https://github.com/5e-bits/5e-database
sites: # List of endpoints to track
  - name: Website
    url: https://www.dnd5eapi.co
    maxResponseTime: 30000
  - name: API (2014 Rules)
    url: https://www.dnd5eapi.co/api/2014
    maxResponseTime: 30000
  - name: GraphQL (2014 Rules)
    url: https://www.dnd5eapi.co/graphql/2014
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"query":"query { backgrounds { index } }"}'
    maxResponseTime: 30000
workflowSchedule:
  graphs: 0 0 * * *
  responseTime: 0 23 * * *
  staticSite: 0 1 * * *
  summary: 0 0 * * *
  updateTemplate: 0 0 * * *
  updates: 0 3 * * *
  uptime: '*/30 * * * *'
